- name: variables to print
  hosts: web
  vars:
    COURSE: "Devops"
    DURATION: "120 hrs"
    TRAINER: "Reddy"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi i am learning {{ COURSE }}, duration is {{ DURATION }}, and trainer {{ TRAINER }}"
