- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0444e2fd1472feabb
    sg_id: "sg-06fbc124ccc63ee9f"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: brahmanayudu.online

  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id}}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id}}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances 
  - name: prnting the ec2 information
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"
  
  - name: creating r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"                 # mysql.daws81.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_instances.results }}"

  - name: creating r53 public records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" # brahmanayudu.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      loop: "{{ ec2_instances.results }}"
      when: item.item == "frontend"